services:
  - type: web
    name: movie-plus-backend
    env: node
    buildCommand: PUPPETEER_CACHE_DIR=/opt/render/.cache npm install && PUPPETEER_CACHE_DIR=/opt/render/.cache npx puppeteer browsers install chrome
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_URL
        value: https://fs17.lol
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache
