services:
  - type: web
    name: movie-plus-backend
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_URL
        value: https://fs17.lol
